name: Write webhook payload

on:
  push:
  pull_request:

permissions:
  contents: write  # Needed to push changes

jobs:
  write-event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT_TOKEN }}  # ✅ Use your PAT secret here

      - name: Create event directory
        run: mkdir -p .github/events

      - name: Write event payload
        run: |
          echo '${{ toJson(github.event) }}' > .github/events/latest-event.json

      - name: Commit and push event file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/events/latest-event.json
          git diff --cached --quiet || git commit -m "Update event payload"
          git push https://x-access-token:${{ secrets.MY_PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
